### ISSUE TITLE
AttributeError: 'StreamToLoguru' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by ikeijo** [Megvii-BaseDetection/YOLOX#1435]
Yesterday I managed to train a custom dataset normally, no issues at all

Tried to train a new version of the dataset today and this error is occurring:

2022-07-13 13:46:41 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (1384), thread 'MainThread' (140279556364160):
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401

ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, ckpt='/content/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/y...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f955ef45200>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f945d629830>
    └ <yolox.core.trainer.Trainer object at 0x7f9457a99850>

  File "/content/YOLOX/yolox/core/trainer.py", line 69, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f9457f66320>
    └ <yolox.core.trainer.Trainer object at 0x7f9457a99850>

  File "/content/YOLOX/yolox/core/trainer.py", line 180, in before_train
    self.tblogger = SummaryWriter(self.file_name)
    │               │             │    └ './YOLOX_outputs/yolox_voc_s'
    │               │             └ <yolox.core.trainer.Trainer object at 0x7f9457a99850>
    │               └ <class 'torch.utils.tensorboard.writer.SummaryWriter'>
    └ <yolox.core.trainer.Trainer object at 0x7f9457a99850>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 220, in __init__
    self._get_file_writer()
    │    └ <function SummaryWriter._get_file_writer at 0x7f945bf58440>
    └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f943dc49710>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 251, in _get_file_writer
    self.flush_secs, self.filename_suffix)
    │    │           │    └ ''
    │    │           └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f943dc49710>
    │    └ 120
    └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f943dc49710>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 61, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
    │        │          │           └ ''
    │        │          └ 120
    │        └ 10
    └ './YOLOX_outputs/yolox_voc_s'

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
    │                    └ './YOLOX_outputs/yolox_voc_s'
    └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
                   │         │      └ 'io'
                   │         └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>
                   └ <function lazy_load.<locals>.wrapper.<locals>.load_once at 0x7f945cc15830>

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
    │     │      │ └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>
    │     │      └ <function lazy_load.<locals>.wrapper.<locals>.load_once at 0x7f945cc157a0>
    │     └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>
    └ {}

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
             └ <function tf at 0x7f945cc15440>

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 47, in <module>
    from tensorflow._api.v2.compat.v1 import lite

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py", line 9, in <module>
    from . import experimental

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py", line 8, in <module>
    from . import authoring

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py", line 8, in <module>
    from tensorflow.lite.python.authoring.authoring import compatible

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/authoring/authoring.py", line 43, in <module>
    from tensorflow.lite.python import convert

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py", line 29, in <module>
    from tensorflow.lite.python import util

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/util.py", line 51, in <module>
    from jax import xla_computation as _xla_computation

  File "/usr/local/lib/python3.7/dist-packages/jax/__init__.py", line 59, in <module>
    from .core import eval_context as ensure_compile_time_eval

  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 47, in <module>
    import jax._src.pretty_printer as pp

  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 56, in <module>
    CAN_USE_COLOR = _can_use_color()
                    └ <function _can_use_color at 0x7f93ed71d680>

  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 54, in _can_use_color
    return sys.stdout.isatty()
           │   └ <yolox.utils.logger.StreamToLoguru object at 0x7f9457a48710>
           └ <module 'sys' (built-in)>

AttributeError: 'StreamToLoguru' object has no attribute 'isatty'

**Comment by ikeijo** [comment]
I've tested it, it works with version 1.15!

https://github.com/googlecolab/colabtools/issues/2914#issuecomment-1183438157
